### ISSUE TITLE
Generated model YAML contains NUL byte

### ISSUE THREAD

**Issue by stronnag** [EdgeTX/edgetx#1116]
Edge main branch of 2021-11-21 (620a43a9c3bc).
Attempted to test loading model YAML into ruby (and python scripts). Both complained of illegal character.  The python example even told me where it was.

In the `logicalSw:` section, there appears an illegal NUL (\000) byte. Indicted as `\0` below in the T12 string in the `2:` element. 
```
logicalSw:
   0:
      func: FUNC_VNEG
      def: tele(11),112
      andsw: !L2
      delay: 50
      duration: 0
   1:
      func: FUNC_VNEG
      def: tele(11),109
      andsw: NONE
      delay: 50
      duration: 0
   2:
      func: FUNC_STICKY
      def: T\00012,NONE
      andsw: SF2
      delay: 0
      duration: 0
```
