### ISSUE TITLE
Special Function Set Timer not saving time Value

### ISSUE THREAD

**Issue by Nerenye** [EdgeTX/edgetx#1130]
Set Timer Special Function resets to 00:00 time Value after changing the model e.g. reloading the model

**General information**
 - EdgeTX version 2.6 from 22.11.2021 compiled for Horus X12S without internal GPS 
 - Hardware Horus X12S

**Comment by pfeerick** [comment]
TX16S and TX12 also. Looks like the time value is missing :grin:

```
customFn: 
   0:
      swtch: SB1
      func: SET_TIMER
      def: Tmr1,1
 ```
