### ISSUE TITLE
[YAML] Problem with !switch elements

### ISSUE THREAD

**Issue by stronnag** [EdgeTX/edgetx#1131]
My aim is to be able to "round trip" YAML files though ruby or python to make systematic cosmetic changes (e.g. globally change widget text colour).

The following construct causes problem:
```
logicalSw:
   0:
      func: FUNC_VNEG
      def: tele(6),1120
      andsw: !L2
      delay: 50
      duration: 0
```
* The standard python YAML parser fails:
```
could not determine a constructor for the tag '!L2'
  in "models-yml/model24.yml", line 434, column 14
```
* The file fails to round trip correctly via the ruby YAML parser. I suspect this is a silent failure in the parser, the round-trip output (YAML => ruby object => YAML) is missing the `andsw:` value:
```
logicalSw:
  0:
    func: FUNC_VNEG
    def: tele(6),1120
    andsw:
    delay: 50
    duration: 0
```
As suspected, the ruby parser dislikes / silently ignores the '!L2' value, ruby object:
```
"logicalSw"=>
  {0=>
    {"func"=>"FUNC_VNEG",
     "def"=>"tele(6),1120",
     "andsw"=>nil,
     "delay"=>50,
     "duration"=>0},

```
