### ISSUE TITLE
Special function override enable state being disabled

### ISSUE THREAD

**Issue by pfeerick** [EdgeTX/edgetx#1136]
The third parameter (enable state) is being ignored, and override special function is staying disabled. 
```
customFn: 
   0:
      swtch: SF0
      func: OVERRIDE_CHANNEL
      def: 0,-100,1
```
