### ISSUE TITLE
Include default Widget Text Color in Theme

### ISSUE THREAD

**Issue by Nerenye** [EdgeTX/edgetx#1151]
Default Widget and TopBar Widget text color seems to be bound to the Color of SECONDARY1
AS the Top Bar is that Color too, you have to change the Color of every widget on every plane if you want to see anything.
Depending on the theme Background it would be helpfull to set the Widget default (text) color in the theme aswell

So i think it would be helpful to create 2 new theme colors to set these Colors directly in the Theme and therefore making widget setup a lot more convenient.

Example:

TOPWIDGET
WIDGET

Sample Screenshot with manually set colors and fitting example theme.yml afterwards

![example](https://user-images.githubusercontent.com/1608923/143419685-d5c6ca36-de3a-46ec-a54a-fa20c7b27418.png)

```yml
---
summary:
  name: Vibrant Blue
  author: Nialija
  info: Vibrant Blue

colors:
  PRIMARY1:   0xF0F4F0
  PRIMARY2:   0x2050D0
  PRIMARY3:   0xE0E4E0
  SECONDARY1: 0x000000
  SECONDARY2: 0x587470
  SECONDARY3: 0x2050D0
  FOCUS:      0x000030
  EDIT:       0xF89800
  ACTIVE:     0x009808
  WARNING:    0xE00000
  DISABLED:   0x888C88
  TOPWIDGET:   0xF0F4F0
  WIDGET:   0x000000
```
