### ISSUE TITLE
SF: GV Adjust not incrementing or decrementing

### ISSUE THREAD

**Issue by pfeerick** [EdgeTX/edgetx#1158]
StonedDawg [reported on discord](https://discord.com/channels/839849772864503828/839849772864503832/913658145941913630) that Adjust GVAR SF (IncDec) is not saving the increment, but it looks like it's a bit more shifty than that... 

![image](https://user-images.githubusercontent.com/5500713/143531719-0be38d51-fffd-41ba-9ce5-3a95d17bcf09.png)

When I set it to GV5, incrementing/decrementing by 10 this was the output - comma missing so enable state invalid, and no reference to what GV to adjust ;)

![image](https://user-images.githubusercontent.com/5500713/143533098-66d59c12-7b27-4129-ae50-ed3f25446883.png)

```yml
customFn: 
   0:
      swtch: SB0
      func: ADJUST_GVAR
      def: IncDec,101
   1:
      swtch: SB2
      func: ADJUST_GVAR
      def: IncDec,-101
```

Cuplrit is probably somewhere around there:
https://github.com/EdgeTX/edgetx/blob/907f7306e772236aab8d468fbc2ab0eab48b3796/radio/src/storage/yaml/yaml_datastructs_funcs.cpp#L1335
