### ISSUE TITLE
INTERNAL_MODULE CRSF not saving receiver ID

### ISSUE THREAD

**Issue by pfeerick** [EdgeTX/edgetx#1258]
When internal module is set to CRSF, the receiver ID is not being saved to yaml, thus model match is not working with ELRS

**Comment by pfeerick** [comment]
Ok, maybe I tell a lie... they are set, and the values are valid. So the next question is then why is ELRS model match not working with internal CRSF. 

```yaml
header: 
   name: "MODEL15"
   modelId: 
      0:
         val: 4
      1:
         val: 20
   bitmap: ""
```
