### ISSUE TITLE
ISRM  shows LR12 instead of ACCST/D16 and works without telemetry even if telem. is set on

### ISSUE THREAD

**Issue by wimalopaan** [EdgeTX/edgetx#1296]
I have a X9d+2019 with ISRM-module (with fw 2.1.6).

With OpenTx all is fine in ACCESS or in ACCST/D16 mode. Telemetry for ACCST works well.

With EdgeTx I get the options ISRM and LR12. Binding to an RX8R with ACCST using LR12 works, it asks aboiut telemetry but then no sensors show up.

**Comment by raphaelcoeffic** [comment]
Where do you see LR12? I can see only `ACCESS` and `ACCST D16`:
<img width="427" alt="Screenshot 2021-12-26 at 15 31 35" src="https://user-images.githubusercontent.com/1050031/147411209-8bcfe248-3f13-44d2-b2fe-4a4f996fad56.png">
<img width="426" alt="Screenshot 2021-12-26 at 15 31 55" src="https://user-images.githubusercontent.com/1050031/147411222-ad1ff8a4-8a82-4bfb-ab4e-b3949d18d3df.png">

Could you please post your `radio.yml` file? Did you compile it yourself, or is it a GH build?

**Comment by wimalopaan** [comment]
```
version: 221
calib: 
   Rud:
      mid: 1000
      spanNeg: 790
      spanPos: 807
   Ele:
      mid: 1021
      spanNeg: 763
      spanPos: 791
   Thr:
      mid: 972
      spanNeg: 781
      spanPos: 777
   Ail:
      mid: 1085
      spanNeg: 837
      spanPos: 754
   POT1:
      mid: 1061
      spanNeg: 1044
      spanPos: 970
   POT2:
      mid: 1037
      spanNeg: 1020
      spanPos: 993
   SLIDER1:
      mid: 1016
      spanNeg: 918
      spanPos: 892
   SLIDER2:
      mid: 1013
      spanNeg: 946
      spanPos: 899
currModel: 0
contrast: 25
vBatWarn: 65
txVoltageCalibration: 0
backlightMode: backlight_mode_all
antennaMode: MODE_PER_MODEL
disableRtcWarning: 0
keysBacklight: 0
internalModule: TYPE_ISRM_PXX2
trainer: 
   mix: 
      0:
         srcChn: 0
         mode: REPL
         studWeight: 100
      1:
         srcChn: 1
         mode: REPL
         studWeight: 100
      2:
         srcChn: 2
         mode: REPL
         studWeight: 100
      3:
         srcChn: 3
         mode: REPL
         studWeight: 100
view: 0
fai: 0
beepMode: mode_nokeys
alarmsFlash: 0
disableMemoryWarning: 0
disableAlarmWarning: 0
stickMode: 0
timezone: 0
adjustRTC: 0
inactivityTimer: 10
telemetryBaudrate: 0
splashMode: 0
hapticMode: mode_nokeys
switchesDelay: 0
lightAutoOff: 2
templateSetup: 0
PPM_Multiplier: 0
hapticLength: 2
beepLength: 2
hapticStrength: 2
gpsFormat: 0
unexpectedShutdown: 0
speakerPitch: 0
speakerVolume: 12
vBatMin: 60
vBatMax: 80
backlightBright: 0
globalTimer: 3549
bluetoothBaudrate: 0
bluetoothMode: TELEMETRY
countryCode: 0
pwrOnSpeed: 0
pwrOffSpeed: 0
imperial: 0
jitterFilter: 0
disableRssiPoweroffAlarm: 0
USBMode: 0
jackMode: 0
ttsLanguage: "en"
beepVolume: 2
wavVolume: 4
varioVolume: 2
backgroundVolume: 3
varioPitch: 0
varioRange: 0
varioRepeat: 0
auxSerialMode: MODE_NONE
slidersConfig: 
   SLIDER1:
      type: with_detent
      name: 
   SLIDER2:
      type: with_detent
      name: 
potsConfig: 
   POT1:
      type: with_detent
      name: 
   POT2:
      type: with_detent
      name: 
backlightColor: 0
switchConfig: 
   SA:
      type: 3pos
      name: 
   SB:
      type: 3pos
      name: 
   SC:
      type: 3pos
      name: 
   SD:
      type: 3pos
      name: 
   SE:
      type: 3pos
      name: 
   SF:
      type: 2pos
      name: 
   SG:
      type: 3pos
      name: 
   SH:
      type: toggle
      name: 
   SI:
      type: toggle
      name: 
bluetoothName: ""
ownerRegistrationID: "\x16\x11829294"
uartSampleMode: 0

```
