### ISSUE TITLE
Wrong display of SI and SJ for Radiomaster TX12 in Companion

### ISSUE THREAD

**Issue by piotrva** [EdgeTX/edgetx#1353]
**Describe the bug**
There is a mismatch between companion and TX12 firmware(yaml format) in naming of additional switches ( #1303 )

**To Reproduce**
As set in Compnion:
![image](https://user-images.githubusercontent.com/5657414/148316716-c607f0cd-1f61-4388-92ae-ba4b89968bc8.png)
Results in YAML:
``` 
- destCh: 9
    srcRaw: SH
    weight: 100
    swtch: NONE
    curve:
      type: 0
      value: 0
    delayUp: 0
    delayDown: 0
    speedUp: 0
    speedDown: 0
    carryTrim: 0
    mltpx: ADD
    mixWarn: 0
    flightModes: 000000000
    offset: 0
    name: PIT
```

While YAML:
```
  - destCh: 9
    srcRaw: SJ
    weight: 100
    swtch: NONE
    curve:
      type: 0
      value: 0
    delayUp: 0
    delayDown: 0
    speedUp: 0
    speedDown: 0
    carryTrim: 0
    mltpx: ADD
    mixWarn: 0
    flightModes: 000000000
    offset: 0
    name: PIT
```
Results in Companion in:
![image](https://user-images.githubusercontent.com/5657414/148316865-7036e4b1-f25b-4d47-a3c3-b89185160402.png)

**General information**
 - EdgeTX: nightly #b5ce1dd (see PR #1341)
 - Hardware: RM TX12
 - Companion: 2.7.0 'dev' 1 January 2020, Windows
