### ISSUE TITLE
Negative GVs are messed up in YAML

### ISSUE THREAD

**Issue by jfrickmann** [EdgeTX/edgetx#1500]
In the attached .etx file I have a model where:
- GV1 is "GVA"
- GV2 is "GVB"

The four first channels each have the following weights in mixes:
1. GVA
2. -GVA
3. GVB
4. -GVB

But when I simulate (and YAML is generated and read by the simulator), I get:
1. GVA
2. GVA
3. GVB
4. -GVA

As you can see, both of the cases with negative sign are incorrect. I discovered the issue when writing models to my Tx after loading 2.6. It looks like it is all the same for TX16S and X9D+ (only verified in simulator). I noticed the issue where GVs were used for adding differential, but it is the same here for weights.
[YAML-test.zip](https://github.com/EdgeTX/edgetx/files/7937151/YAML-test.zip)

**Comment by pfeerick** [comment]
Looks like companion is generating the correct code

```
mixData:
  - destCh: 0
    srcRaw: I0
    weight: GV1
...
  - destCh: 1
    srcRaw: I1
    weight: -GV1
...
  - destCh: 2
    srcRaw: I2
    weight: GV2
...
  - destCh: 3
    srcRaw: I3
    weight: -GV2
```

but the radios isn't, and thus probably also why it's reading it wrong...
```
mixData: 
 -
   weight: GV1
   destCh: 0
   srcRaw: I0
...
 -
   weight: -GV2
   destCh: 1
   srcRaw: I1
...
 -
   weight: GV2
   destCh: 2
   srcRaw: I2
...
 -
   weight: -GV3
   destCh: 3
   srcRaw: I3
```
