### ISSUE TITLE
Ghost 12 bit - Companion support needed

### ISSUE THREAD

**Issue by pfeerick** [EdgeTX/edgetx#1510]
With the introduction of #1233 & #1377, Companion needs to be taught about the new Ghost module setting:
```
moduleData: 
   1:
      type: TYPE_GHOST
      subType: 0
      channelsStart: 0
      channelsCount: 16
      failsafeMode: NOT_SET
      mod: 
         ghost: 
            raw12bits: 1
```
