### ISSUE TITLE
Firmware/companion yaml node name mismatch for mixer script config

### ISSUE THREAD

**Issue by bug400** [EdgeTX/edgetx#2015]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Companion

### Current Behavior

If you transfer model and radio data from a Taranis X7/ACCESS to companion, then the configuration for mixer scripts is lost. The model yaml files stored in the etx file have no mixer script configuration any more.

I noticed that the firmware stores mixer script configuration under the node name "scriptsData".
In the file companion/src/firmwares/edgetx/yaml_modeldata.cpp the node name "scriptData" is used instead for mixer script configuration.

If I fix this and build my own companion/simulator version everything works as it should.

### Expected Behavior

Mixer script configuration is handled correctly, if reading or writing yaml configuration files in companion.

### Steps To Reproduce

1. Have a model on TARANIS X7/ACCESS with a configured mixer script.
2. Connect radio to PC
3. Start companion
4. Read radio and model data
5. Store them as an "etx"- file
6. Inspect "etx"-file content-> model yaml-files do not have any mixer script configuration data.

### Version

Other (Please specify below)

### Transmitter

FrSky Q X7 / Q X7S (ACCESS)

### Anything else?

Software Version is 2.7.1.
The node name mismatch in yaml_modeldata.cpp is still present in the current github repo.

**Comment by pfeerick** [comment]
Thanks for the report @bug400, can repo that. Just need to figure out best way to fix it. 

@elecpower While I think this is originally / technically a bug in the radio firmware - originating from here

https://github.com/EdgeTX/edgetx/blob/10b16337ca04705856a23fac81664f38c61d8e5a/radio/src/datastructs_private.h#L610

I think the path of least resistance is to fix it in Companion by adding the missing `s` (rather than having to also add code to correct it on the radio) ... i.e. Maybe as simple as this?

```diff
diff --git a/companion/src/firmwares/edgetx/yaml_modeldata.cpp b/companion/src/firmwares/edgetx/yaml_modeldata.cpp
index c99366b3f..1e36d2ab7 100644
--- a/companion/src/firmwares/edgetx/yaml_modeldata.cpp
+++ b/companion/src/firmwares/edgetx/yaml_modeldata.cpp
@@ -938,7 +938,7 @@ Node convert<ModelData>::encode(const ModelData& rhs)
 
   for (int i=0; i<CPN_MAX_SCRIPTS; i++) {
     if (strlen(rhs.scriptData[i].filename) > 0) {
-      node["scriptData"][std::to_string(i)] = rhs.scriptData[i];
+      node["scriptsData"][std::to_string(i)] = rhs.scriptData[i];
     }
   }
 
@@ -1135,7 +1135,7 @@ bool convert<ModelData>::decode(const Node& node, ModelData& rhs)
     trainer["pulsePol"] >> rhs.moduleData[2].ppm.pulsePol;
   }
 
-  node["scriptData"] >> rhs.scriptData;
+  node["scriptsData"] >> rhs.scriptData;
   node["telemetrySensors"] >> rhs.sensorData;
 
   node["toplcdTimer"] >> rhs.toplcdTimer;
   ```

Plus I think there is still a bug in how Companion is handling it so it needs some TLC - it is hard-coded for 6 elements, rather than only adding the number that exist / were read in. 

https://github.com/EdgeTX/edgetx/blob/10b16337ca04705856a23fac81664f38c61d8e5a/companion/src/firmwares/edgetx/yaml_modeldata.cpp#L547-L549

which means after the above change, Companion changes

```yaml
scriptsData: 
   0:
      file: "GtStd"
      name: "lua1"
      inputs: 
         0:
            u: 
               value: 1
         1:
            u: 
               value: 5
   1:
      file: "GtStd"
      name: "lua2"
      inputs: 
         0:
            u: 
               value: 2
         1:
            u: 
               value: 15
```

to

```yaml
scriptsData:
  0:
    file: GtStd
    name: lua1
    inputs:
      0:
        u:
          value: 1
      1:
        u:
          value: 5
      2:
        u:
          value: -1499536720
      3:
        u:
          value: 45
      4:
        u:
          value: -1499537072
      5:
        u:
          value: -1
  1:
    file: GtStd
    name: lua2
    inputs:
      0:
        u:
          value: 2
      1:
        u:
          value: 15
      2:
        u:
          value: -1499536720
      3:
        u:
          value: 45
      4:
        u:
          value: -1499537072
      5:
        u:
          value: -1
```

... that's the correct values for 0 and 1, and bonus garbage for the other four entries which don't really exist. 😆 

For reference, this was using a TX16 `-DLUA_MIXER=Y` build, and using [this mixer script](https://raw.githubusercontent.com/RCdiy/OpenTXLua/master/MIXES/GtStd.lua). More than happy to test for you if you can do the hard stuff :grin:
