### ISSUE TITLE
Companion not reading/writing receiverName value for ACCESS

### ISSUE THREAD

**Issue by rburrow87** [EdgeTX/edgetx#2018]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Companion

### Current Behavior

When Companion reads in a model using ACCESS protocol, it does not read in the receiverName value and so it does not write it back out when you push the config back to the transmitter.

Unsure if this is a black and white radio specific issue or if the color screen ACCESS radios have the same issue.

### Expected Behavior

receiverName should be carried into Companion and written back out when writing to the TX.

### Steps To Reproduce

 - Register and bind an RX with ACCESS
 - Read the models into Companion (see that Receiver 1 is blank in Companion when it shouldn't be)
 - Write back to the TX (see that all the receivers are now blank in model settings)

### Version

2.7.1

### Transmitter

FrSky X9D+2019

### Anything else?

Module data before reading into Companion:
```
moduleData: 
   0:
      type: TYPE_ISRM_PXX2
      subType: ACCESS
      channelsStart: 0
      channelsCount: 8
      failsafeMode: NOPULSES
      mod: 
         pxx2: 
            receivers: 1
            racingMode: 0
            receiverName: 
               0:
                  val: "Slick85 "
```

Module data after writing back to TX from Companion, note receiverName val is missing:
```
moduleData:
  0:
    type: TYPE_ISRM_PXX2
    subType: ACCESS
    channelsStart: 0
    channelsCount: 8
    failsafeMode: NOPULSES
    mod:
      pxx2:
        receivers: 1
        racingMode: 0
        receiverName:
          0: ""
```
