### ISSUE TITLE
ACCESS receiver count value incorrect in model yml file

### ISSUE THREAD

**Issue by rburrow87** [EdgeTX/edgetx#2022]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

With 1 receiver bound, the `receivers` value is 1. With 2 receivers it goes to 3, and with 3 receivers it jumps to 7.

### Expected Behavior

It should have a value of 1, 2, or 3.

### Steps To Reproduce

Register/bind 2 or 3 receivers and look at the `receivers` value under `moduleData` of the model yml file.

### Version

2.7.1

### Transmitter

FrSky X9D+2019

### Anything else?

I'm guessing this is not intended behavior, but if it is, #2019 will need to be adjusted to count receivers the same way.

1 receiver bound, `receivers: 1`
```
moduleData: 
   0:
      type: TYPE_ISRM_PXX2
      subType: ACCESS
      channelsStart: 0
      channelsCount: 8
      failsafeMode: NOPULSES
      mod: 
         pxx2: 
            receivers: 1
            racingMode: 0
            receiverName: 
               0:
                  val: "RX4R    "
```

2 receivers bound, `receivers: 3`
```
moduleData: 
   0:
      type: TYPE_ISRM_PXX2
      subType: ACCESS
      channelsStart: 0
      channelsCount: 8
      failsafeMode: NOPULSES
      mod: 
         pxx2: 
            receivers: 3
            racingMode: 0
            receiverName: 
               0:
                  val: "RX4R    "
               1:
                  val: "R4      "
```

3 receivers bound, `receivers: 7`
```
moduleData: 
   0:
      type: TYPE_ISRM_PXX2
      subType: ACCESS
      channelsStart: 0
      channelsCount: 8
      failsafeMode: NOPULSES
      mod: 
         pxx2: 
            receivers: 7
            racingMode: 0
            receiverName: 
               0:
                  val: "RX4R    "
               1:
                  val: "R4      "
               2:
                  val: "SpecV2 "
```
