### ISSUE TITLE
Trainer Channel Source mismatched

### ISSUE THREAD

**Issue by TheIsotopes** [EdgeTX/edgetx#2025]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Companion

### Current Behavior

Trainer Channel Source readout from receiver is mismatched on Companion.
On my TX i'm using AETR but Companion reads out / shows RETA.
After Write back to TX all is good.
Imo it should an bug on Companion side.

### Expected Behavior

Same Trainer Channel Source on TX and Companion.

### Steps To Reproduce

- use Trainer Channel Source AETR on Companion
- write this to TX
- compare Trainer Channel Source output from TX and Companion

### Version

2.7.1

### Transmitter

Radiomaster TX16S

**Comment by TheIsotopes** [comment]
Nothing has changed in the current v2.8.0-RC1 either. It's a pity!
However, this only seems to affect color RX.

**Comment by pfeerick** [comment]
Well, you haven't bumped the issue at all to see if there was any comment either ;) 

So by "trainer channel source output" you mean this?

![image](https://user-images.githubusercontent.com/5500713/192740254-024c0068-5833-4092-94d4-4b0212905806.png)

**Comment by TheIsotopes** [comment]
Yes, exactly this.

**Comment by pfeerick** [comment]
Ok, I can reproduce this, and from the looks of the values I think the radio firmware has been writing it out of order, and companion is correct. 

I'm using TAER  channel order. So my trainer setting should be 
![image](https://user-images.githubusercontent.com/5500713/192741981-2dfb2682-ba40-4de7-80d6-84ca9c12623d.png) 
![image](https://user-images.githubusercontent.com/5500713/192742213-ce1b0e11-aab7-45ca-82aa-76a1bca168c3.png)

However, when I read the radio with Companion I get
![image](https://user-images.githubusercontent.com/5500713/192743378-5bb9866e-2847-401e-a377-49d93baeb3ad.png)

And I have no idea atm how the heck these settings correspond with the radio settings...
![image](https://user-images.githubusercontent.com/5500713/192744557-25cc5b08-3586-46e6-bf3b-4050471b20eb.png)

since the values Companion wrote make more sense - 0(R) is CH3+1, 1(E) is CH2+1, 2(T) is CH0+1 and 3(A) is CH1+1
```yml
  mix:
    0: 
      srcChn: 3
      mode: REPL
      studWeight: 100
    1:
      srcChn: 2
      mode: REPL
      studWeight: 100
    2:
      srcChn: 0
      mode: REPL
      studWeight: 100
    3:
      srcChn: 1
      mode: REPL
      studWeight: 100
```
