### ISSUE TITLE
Have YAML file on retain comments

### ISSUE THREAD

**Issue by rdeanchurch** [EdgeTX/edgetx#2141]
### Is there an existing issue for this feature request?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

Currently comments are stripped off and discarded.  
This means comments can not be used to document or as an aid to editing the YAML files for modelxx.yml.

### Describe the solution you'd like

Allow # comments to be retained after being processed by the Tx O.S..

### Additional context

```
# timers...Begin...This block of YAML can set up three timers for a model by copying it to a
#   new model after the 'header: object so all models have a consistent set of timers
timers:
  0:     # TIMER 1
    swtch: SF0  # Sw SF down is used as a Throttle safety, up is armed
    mode: ON
    name: Flight
    minuteBeep: 0
    countdownBeep: 0
    start: 0
    persistent: 0
    countdownStart: 0
    value: 0
  1:
    swtch: SF0
    mode: THR
    name: Throttle
    minuteBeep: 0
    countdownBeep: 0
    start: 0
    persistent: 0
    countdownStart: 0
    value: 0
  2:
    swtch: NONE
    mode: ON
    name: Toal
    minuteBeep: 0
    countdownBeep: 0
    start: 0
    persistent: 1
    countdownStart: 0
    value: 0
# end  timers block 
```
