### ISSUE TITLE
Default input names are truncated

### ISSUE THREAD

**Issue by pfeerick** [EdgeTX/edgetx#2389]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

Default input names are a letter shorter than they used to be, and on Companion are replaced with what looks like a Chinese symbol.
```yaml
inputNames: 
   0:
      val: "\x89Ai"
   1:
      val: "\x89Th"
   2:
      val: "\x89El"
   3:
      val: "\x89Ru"
```

### Expected Behavior

That the names be three characters... like so:

```yml
inputNames: 
   0:
      val: "Thr"
   1:
      val: "Ail"
   2:
      val: "Ele"
   3:
      val: "Rud"
```

### Steps To Reproduce

1. Use recent nightly, or 2.8.0 RC1
2. Create a new model on the transmitter
3. Have a look at the inputs screen - I *think* that looks right - needs checking
4. Have a look at the mixes screen, third letter is now missing, can't remember if it showed two symbols before. 

### Version

Nightly (Please give date/commit below)

### Transmitter

RadioMaster TX12 / TX12MK2
Flysky NV14

### Anything else?

First spotted when testing iFlight Commando companion PR, then realised was a `main` problem... unicode/utf8 related... 
Edit: Just check Flysky NV14 - it's showing `Th` instead of `Thr` also, so might be the same.
