### ISSUE TITLE
Companion X10s Express, ISRM receiver name missing

### ISSUE THREAD

**Issue by mha1** [EdgeTX/edgetx#3273]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Companion

### Current Behavior

Attached .yml was generated with a X10S Express (int. ISRM) using 2.8.1. It has one receiver listed and named. 

```
moduleData: 
   0:
      type: TYPE_ISRM_PXX2
      subType: ACCESS
      channelsStart: 0
      channelsCount: 8
      failsafeMode: CUSTOM
      mod: 
         pxx2: 
            receivers: 0
            racingMode: 0
            receiverName: 
               0:
                  val: "RX4R    "
failsafeChannels: 
   1:
      val: -348
   2:
      val: -41
```

After importing the model file with Companion 2.8.1 (settings X10s Express) no receiver name is listed. Saving the file from Companion results in .yml with no receiver name.

```
moduleData:
  0:
    type: TYPE_ISRM_PXX2
    subType: ACCESS
    channelsStart: 0
    channelsCount: 8
    failsafeMode: CUSTOM
    mod:
      pxx2:
        receivers: 0
        racingMode: 0
failsafeChannels:
  1:
    val: -348
  2:
    val: -41
```

[model1.yml.txt](https://github.com/EdgeTX/edgetx/files/10838053/model1.yml.txt)

![image](https://user-images.githubusercontent.com/5615068/221525296-64ddac5b-fb6d-4da1-9ddb-9817bfa82f6b.png)

### Expected Behavior

Receiver name is listed and can be edited in Companion
Saving the imported model.yml should not delete receiver names

### Steps To Reproduce

1. Set Companion to X10s Express
2. Import model.yml
3. Check Setup tab for receiver name
4. Save model.yml
5. Check model.yml for receiver name tag

### Version

2.8.0

### Transmitter

FrSky X10 Express / X10S Express (ACCESS)

### Anything else?

FW and Companion version 2.8.1
