### ISSUE TITLE
Could not save for pre-release multiprotocol

### ISSUE THREAD

**Issue by rdba2k** [EdgeTX/edgetx#4144]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

I use pre-release multiprotocol, for example,FX/9630. I can change the setting for external module in model A, then I switch to model B, then switch back to model A, the configuration in model A is lost. If I use FX/860, the configuration is kept. Edgetx 2.8.5 seems no problem.

### Expected Behavior

Maybe edgetx 2.9 checks the multiprotocol and invalidate the protocol not defined in its header files, which prevents us to use latest multiprotocol version than the release version when 2.9 is built.

### Steps To Reproduce

Described in current behavior section

### Version

2.9.0

### Transmitter

Radiomaster TX16S / TX16SMK2

**Comment by pfeerick** [comment]
It _should_ be using the protocols as reported by the module as supported, and only falling back to the pre-defined list if the module is not present or not communicating. @mha1 Any ideas?

**Comment by mha1** [comment]
https://github.com/EdgeTX/edgetx/blob/e8077021f6f7722216bdd36f7962e5c38f60117e/radio/src/MultiSubtypeDefs.h#L221

change this line to read "2," instead of "1,"

**Comment by 3djc** [comment]
> https://github.com/EdgeTX/edgetx/blob/e8077021f6f7722216bdd36f7962e5c38f60117e/radio/src/MultiSubtypeDefs.h#L221
> 
> change this line to read "2," instead of "1,"

While this hides the issue, it is likely not the right fix. The radio should get updated list and handle it gracefully without code change

**Comment by mha1** [comment]
those definitions must match multi.txt otherwise yaml can't decode the saved subprotocol when loading the modelxx.yml

**Comment by 3djc** [comment]
Then that YAML part is wrong and needs to be fixed. The multi needs to be able to list new protocols independently of edgetx code

**Comment by raphaelcoeffic** [comment]
> those definitions must match multi.txt otherwise yaml can't decode the saved subprotocol when loading the modelxx.yml

Since when? AFAIK, only proto numbers are saved.

**Comment by mha1** [comment]
```
moduleData: 
   0:
      type: TYPE_MULTIMODULE
      subType: 57,0
      channelsStart: 0
      channelsCount: 16
```
subtype holds protocol and subprotocol. In this case 57 -> protocol HoTT, 0 -> subprotocol SYNC

I shouldn't answer reading stuff on my phone and answer on the phone. Question number 1 needs to be which MPM firmware was used and does this firmware send the added third subprotocol. If not you fall back to the internal definitions and in this case the definitions need to match, i.e. lines 133 (defines 3 sub protocols) and 221 (also needs to state we have 3 subprotocols - counting starts from zero hence 1 -> 2).

**Comment by mha1** [comment]
@rdba2k just out of curiosity: after switching back to model A you see Mode: MULTI FX and RF Protocol: <empty> in the External RF setup page, correct? Have you tried connecting the receiver? It should still work as if 9630 was selected. Does it?

**Comment by mha1** [comment]
I can confirm the reported problem. I tried this with 2.9.1 and the latest MPM merge build (1.3.3.32). EdgeTX scans the MPM and the MPM correctly sends the subProto list for protocol FX.  FX/9630 can be selected (no need for #4145). Protocol data is stored in model.yaml as expected (58->FX, 2->9630):

```
moduleData: 
   0:
      type: TYPE_MULTIMODULE
      subType: 58,2
      channelsStart: 0
      channelsCount: 16
      failsafeMode: NOT_SET
```

Then shutting down the radio and starting it up again clears the models module data:
moduleData: 

```
   0:
      type: TYPE_NONE
      subType: 0
      channelsStart: 0
      channelsCount: 16
      failsafeMode: NOT_SET 
```

Need to find out why.
