### ISSUE TITLE
Calibration will breaks for invalid calibration data

### ISSUE THREAD

**Issue by richardclli** [EdgeTX/edgetx#4251]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

I tried this in EL18 with these calibration data in radio.yml

```yaml
calib: 
   LH:
      mid: 0
      spanNeg: 0
      spanPos: 1253
   LV:
      mid: 0
      spanNeg: 1
      spanPos: 1240
   RV:
      mid: 0
      spanNeg: 1
      spanPos: 1273
   RH:
      mid: 0
      spanNeg: 1
      spanPos: 1304
   P1:
      mid: 1009
      spanNeg: 994
      spanPos: 1022
   P2:
      mid: -2000
      spanNeg: 966
      spanPos: 1050
```

And you can never get the radio calibrated through the calibration procedures.

### Expected Behavior

Calibration procedures can always works no matter what is the current calibration data is.

### Steps To Reproduce

1. Copy the calibration data to radio.yml
2. Try to do calibration

### Version

Nightly (Please give date/commit below)

### Transmitter

Flysky EL18

### Operating System (OS)

Windows

### OS Version

main as of date 2023-10-26

### Anything else?
[](url)
_No response_
